# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27be531a9d9d7fa2910823d7ef6a780f131daac65275b1882810e4a72751f9519e239d2aa6c8ee20b171e3a47c6d1fcda96aa42e1746c6148163b72a46df55b2

test:
  secret_key_base: 86edefa23258bbb8299749197d907d9edd327ef834afb9f03b7e2aa93c45f93607df1a6a46604d47fcd36bd1385aba65f07ab2cfb06a362027e0b64effd71183

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
